s3:
    endpoint-url: ${S3_ENDPOINT_URL}
    secret-key: ${S3_SECRET_KEY}
    access-key: ${S3_ACCESS_KEY}
    content-bucket-name: ${S3_BUCKET_CONTENTS_NAME:contents}

spring:
    application:
        name: ArticleService
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DB_PASSWORD}
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
